language: php

php:
  - 5.6
  - 7.0.9
  - 7.1
  - nightly
  - hhvm-3.12

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm-3.12
  fast_finish: true

addons:
  hostname: TestingGCE
  hosts:
    - TestingGCE

sudo: required

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo apt-get update --yes
  - sudo apt-get install --yes net-tools wget
  - composer self-update

install: composer install --no-interaction

script:
  - vendor/bin/phpunit test --coverage-clover test/clover.xml --configuration test/phpunit.xml

after_script:
  - cat test/testListeningScenario_profiling.txt
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ $(phpenv version-name) = "5.6" ]; then php ocular.phar code-coverage:upload --format=php-clover test/clover.xml --revision=$TRAVIS_COMMIT; fi
  - if [ $(phpenv version-name) = "7.0" ]; then php ocular.phar code-coverage:upload --format=php-clover test/clover.xml --revision=$TRAVIS_COMMIT; fi
  - if [ $(phpenv version-name) = "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover test/clover.xml --revision=$TRAVIS_COMMIT; fi
